
services:
  postgres:
    image: postgis/postgis:latest
    container_name: my_postgres
    environment:
      - POSTGRES_DB=bank_services
      - POSTGRES_USER=bankusers
      - POSTGRES_PASSWORD=123456Bank
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - '5050:80'